import type { Metadata } from "next";
import {
  ColorSchemeScript,
  MantineProvider,
  mantineHtmlProps,
} from "@mantine/core";
import { Toaster } from "sonner";
import Providers from "./providers";
import { theme } from "./theme";

// Estilos
import "./globals.css";
import "@mantine/core/styles.css";

// Fuentes variables
import "@fontsource-variable/montserrat";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" {...mantineHtmlProps}>
      <head>
        <ColorSchemeScript />
      </head>
      <body className="font-inter antialiased">
        <MantineProvider theme={theme}>
          <Providers>
            {children}
            <Toaster richColors expand={true} position="bottom-right" />
          </Providers>
        </MantineProvider>
      </body>
    </html>
  );
}
